env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:jest/recommended
plugins:
  - jest
parserOptions:
  ecmaVersion: latest
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always

